version: '3.8'
 
networks:
 default:
   external: false
   name: api-postgres
 
services:
  api-postgres:
   image: "postgres:13-alpine"
   command: postgres -c 'max_connections=1000'
   restart: always
   container_name: api-postgres
   environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_DB=api-postgres_db
   volumes:
     - ./db_data:/var/lib/postgresql/data
   ports:
     - "5430:5432"